import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { HiShoppingBag } from "react-icons/hi";
import products from "../data/products.json";

export async function getStaticProps(context) {
  return {
    props: { products }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="py-4 bg-gray-50 shadow">
        <div className="container">
          <nav className="flex items-center justify-between">
            <div className="logo">
              <Link href="/">
                <a className="text-xl font-bold uppercase text-orange-500">
                  Logo
                </a>
              </Link>
            </div>
            <div>
              <Link href="/">
                <a className="text-xl  text-orange-500">
                  <HiShoppingBag />
                </a>
              </Link>
            </div>
          </nav>
        </div>
      </header>

      <main>
        <section className="py-10">
          <div className="container">
            <div className="grid grid-cols-2 gap-5 md:grid-cols-3 lg:grid-cols-4">
              {props.products.map((product) => {
                return (
                  <div
                    className="md:cols-span-1 w-full border shadow p-5"
                    key={product.id}
                  >
                    <div className="img-area mb-5 text-center">
                      <Link href={`/product/${product.id}`}>
                        <a>
                          <Image
                            src={product.image}
                            alt={product.title}
                            height={90}
                            width={90}
                            className="text-center object-contain "
                          />
                        </a>
                      </Link>
                    </div>
                    <div className="des mx-auto text-center flex flex-col gap-3">
                      <Link href={`/product/${product.id}`}>
                        <a className="text-center text-base font-bold text-black">
                          {product.title.split(" ").slice(0, 5).join(" ")}
                        </a>
                      </Link>

                      <h4>Price: ${product.price}</h4>
                      <button className="py-2 px-5 mx-auto bg-black rounded text-white">
                        Add to cart
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
